### ISSUE TITLE
Mapped folders not showing up

### ISSUE THREAD

**Issue by LAB02-Admin** [hasan-hasanov/Boxer#2]
Hi @hasan-hasanov,

For starters: thank you so much for this package! It's really perfect for fast testing. 

However, I can't get my host folders to show up. This is a deserialization of the `IOptions` object I use:

```json
{
  "SandboxDesktopLocation": "C:\\Users\\WDAGUtilityAccount\\Desktop\\",
  "SandboxConfigurationFileName": "sandbox.wsb",
  "RootFilesDirectoryLocation": "C:\\Users\\{my_local_user}\\AppData\\Local\\Temp\\Sandbox",
  "RootSandboxFilesDirectoryLocation": "C:\\Users\\WDAGUtilityAccount\\Desktop\\Sandbox\\",
  "VGpu": 0,
  "Networking": 1,
  "UserMappedDirectories": [
    {
      "HostFolder": "D:\\Temp",
      "SandboxFolder": "C:\\Users\\WDAGUtilityAccount\\Desktop\\Temp\\",
      "ReadOnly": "true"
    }
  ],
  "AudioInput": 2,
  "VideoInput": 2,
  "ProtectedClient": 2,
  "PrinterRedirection": 2,
  "ClipboardRedirection": 1,
  "MemoryInMB": 0
}
```

And this is the content of the `sandbox.wsb` file it references:

```xml
<Configuration>
  <VGpu>Disabled</VGpu>
  <Networking>Default</Networking>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>C:\Users\{my_local_user}\AppData\Local\Temp\Sandbox</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\Desktop\Sandbox\</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -ExecutionPolicy Bypass -File C:\Users\WDAGUtilityAccount\Desktop\Sandbox\MainScript.ps1 3&gt;&amp;1 2&gt;&amp;1 &gt; "C:\Users\WDAGUtilityAccount\Desktop\Log_637825178861311088.txt"</Command>
  </LogonCommand>
  <AudioInput>Default</AudioInput>
  <VideoInput>Default</VideoInput>
  <ProtectedClient>Default</ProtectedClient>
  <PrinterRedirection>Default</PrinterRedirection>
  <ClipboardRedirection>Default</ClipboardRedirection>
  <MemoryInMB>0</MemoryInMB>
</Configuration>
```

As you can see, my mapped folder isn't being added (I only noticed this while making this bug report by the way). If I manually edit `sandbox.wsb`, and add my mapped folder, it works just fine.

Any idea what I'm missing, am I not configuring the sandbox right?

Thanks!

**Comment by LAB02-Admin** [comment]
I seem to have it working now. I have to add my `IOptions` object both to the `new Sandbox` initializer, ánd to the `ISandboxConfigurationBuilder` object:

```C#
// prepare sandbox
ISandboxConfigurationBuilder configurationBuilder = new SandboxConfigurationBuilder(options);
var sandbox = new Sandbox(options, configurationBuilder);
```

What's the point of the first `IOptions` parameter of `new Sandbox()`? It doesn't seem to be used.

**Comment by hasan-hasanov** [comment]
Hi @LAB02-Admin

Thank you very much for reaching out. I agree with you that it should have worked without configuration builder and with just options. It must be a bug which I will check out as soon as I can.

As you stated it out it needs some refactoring which currently I do not have very much free time.

Boxer is a complete CLI application, if you need only a library for custom work you can use [ScoopBox](https://github.com/hasan-hasanov/ScoopBox). It is a library which Boxer utilizes.

**Comment by LAB02-Admin** [comment]
Oops, I posted in the wrong repo - sorry! I'm using ScoopBox. 

I'll close this, it's working fine now :)
